### ISSUE TITLE
Watch for new outputs

### ISSUE THREAD

**Issue by MaxVerevkin** [jeremija/wl-gammarelay#3]
The daemon only sets the color for outputs that were presented on the startup: if I start the daemon, then connect a new display and then try to modify the color, newly connected display is unaffected.

**Comment by jeremija** [comment]
Thanks for the report. I figured that might be the case.

Are you aware of any utility that does detect new displays? I'm not that familiar with wayland so it would be useful to see how it's done.

**Comment by MaxVerevkin** [comment]
> I'm not that familiar with wayland so it would be useful to see how it's done.

Neither am I. I'll post here if I'll find something.
