### ISSUE TITLE
does wl-gammarelay work on Gnome?

### ISSUE THREAD

**Issue by joh4nd** [jeremija/wl-gammarelay#8]
As a Debian user, I am curious whether wl-gammarelay works on Gnome. Does it?

I am [looking](https://unix.stackexchange.com/q/743252/530603) for a Wayland and Gnome compatible tool to invert the screen or windows (e.g. from light to dark) using keybindings.

**Comment by MaxVerevkin** [comment]
No, since Gnome does not implement `wlr-gamma-control-unstable-v1` (`wl-gammarelay` and `wl-gammarelay-rs` use the same Wayland protocol).

**Comment by joh4nd** [comment]
Thanks Max, yet :-(
